### ISSUE TITLE
using gmailr with requirejs

### ISSUE THREAD

**Issue by ghost** [joscha/gmailr#2]
I have the following:

**manifest.json:**

``` json
{
  "name": "Dev",
  "version": "1.0",
  "description": "Dev testing.",
  "content_scripts": [
    {
      "matches": [
        "*://mail.google.com/*"
      ],
      "js": [
        "lib/js/bower_components/requirejs/require.js",
        "lib/js/vendor/require-cs.js",
        "src/js/main.js"
      ],
      "css": [
        "lib/stylesheets/smacss/main.css"
      ],
      "run_at": "document_end"
    }
  ],
  "web_accessible_resources": [
    "lib/js/bower_components/requirejs-text/text.js",
    "lib/js/bower_components/jquery/jquery.min.js",
    "lib/js/bower_components/underscore/underscore-min.js",
    "lib/js/bower_components/backbone/backbone.js",
    "lib/js/vendor/gmailr/chrome/lib/gmailr.js",
    "lib/js/vendor/gmailr/chrome/lib/jquery-bbq/jquery.ba-bbq.min.js",
    "lib/js/vendor/gmailui/lib/GMailUI.js",
    "src/js/app.js"
  ],
  "manifest_version": 2,
  "permissions": [
    "*://mail.google.com/*",
    "*://www.jdev.com/*"
  ]
}
```

**lib/js/vendor/require-cs.js:**

``` javascript
// from https://github.com/nonowarn/content-script-with-requirejs/blob/master/lib/require-cs.js
require.load = function (context, moduleName, url) {
  var xhr = new XMLHttpRequest(),
      evalResponseText = function(xhr) {
        eval(xhr.responseText);
        context.completeLoad(moduleName);
      };

  xhr.open("GET", url, true);
  xhr.onreadystatechange = function (e) {
    if (xhr.readyState === 4 && xhr.status === 200) {
      // we have to specifically pass the window context or underscore
      // will fail since it defines "root = this"
      evalResponseText.call(window, xhr);
    }
  };
  xhr.send(null);
};
```

**src/js/main.js:**

``` javascript
require.config({
    baseUrl: chrome.extension.getURL('src/js/'),
    paths: {
        jquery: '../../lib/js/bower_components/jquery/jquery.min',
        underscore: '../../lib/js/bower_components/underscore/underscore-min',
        backbone: '../../lib/js/bower_components/backbone/backbone',
        gmailr: '../../lib/js/vendor/gmailr/chrome/lib/gmailr',
        jquery_bbq: '../../lib/js/vendor/gmailr/chrome/lib/jquery-bbq/jquery.ba-bbq.min',
        gmailui: '../../lib/js/vendor/gmailui/lib/GMailUI',
        text: '../../lib/js/bower_components/requirejs-text/text.js',
        templates: 'templates'
    },
    shim: {
        'backbone': {
            deps: ['underscore', 'jquery'],
            exports: 'Backbone'
        },
        'underscore': {
            exports: '_'
        },
        'gmailr': {
            deps: ['jquery', 'jquery_bbq'],
            exports: 'Gmailr'
        }
    }
});

require([
    'app',
], function(App){
    App.init();
});
```

**src/js/app.js:**

``` javascript
define([
    'jquery',
    'underscore',
    'backbone',
    'gmailr',
], function($, _, Backbone, Gmailr) {

    'use strict';

    Gmailr.debug = true;

    var init = function() {
        console.log('loading extension...');

        // init gmailr api
        Gmailr.init(function(G) {
            console.log('loading gmailr...');

            G.observe(Gmailr.EVENT_DRAFT_SAVE, function(details) {
                console.log('draft saved', details);
            });

            G.observe(Gmailr.EVENT_COMPOSE, function(details) {
                console.log('message sent', details);
            });

        });

    };

    return {
        init: init
    };

});
```

The app loads, gmailr loads, I see success messages around "delayed loader" etc in the console, but it doesn't look like the XHRWatcher is working properly. When a draft is saved or I send a message, I don't see any of the logging I added to gmailr. When the message is sent though, I do see a message from gmailr about the unread count of the inbox changing.

I think this might have something to do with the context of where the gmailr script is getting loaded. I've had several issues with that in working with content_scripts. I see in gmailr/bootstrap, before loading the files you check `top.document === document`, but I'm not exactly sure why that is happening, or what the proper way to get require.js to do that.

I'm far from a js expert, so I was wondering if you could shed some light here.

Ideally, I'd like to see gmailr evolve into a library that could easily be included with any browser extension: chrome, firefox, safari etc. instead of just the boilerplate chrome structure that it serves as now.

If my description isn't clear enough, I can put together a repo quickly that will repro the issue.

**Comment by joscha** [comment]
At first glance I think you might right about it being a context problem. Can you try renaming the "win" shortened form of the closured window object into "window" and see if it works then?

**Comment by ghost** [comment]
you mean here: https://github.com/joscha/gmailr/blob/master/chrome/src/gmailr.coffee#L20?

**Comment by joscha** [comment]
yes, set a debugger statement right after and see if the HTTPReq object is properly on it

**Comment by ghost** [comment]
with debugger after statement:

```
> win.name
"j1r0j8utu6a9gq"
// matches the name of the iframe "js_frame"
> win.XMLHttpRequest 
function XMLHttpRequest() { [native code] }
```

One thing I notice is that when loaded via requirejs, the "win" object doesn't have all the compiled functions that gmail is attaching to it. If I load gmailr via yepnope, the "win" object has significantly more functions attached to it ie. (A0a, A1a etc.) and overriding XMLHttpRequest works perfectly.

Since we're explicitly fetching the iframes window though, I don't see why it matters where we init gmailr, or how yepnope and requirejs are doing it differently.

The sole reason I'm using requirejs in the first place is to get access to: https://github.com/requirejs/text and the ability to load templates within the content_script backbone models. At this point, I would settle for an alternative to that functionality and go back to yepnope which works great.

**Comment by joscha** [comment]
my guess is, that the reason is, that with yepnope the GMailr script gets directly injected into the content frame. If you have the code above in a repository, I can have a look at the weekend whether we can tweak it in a way that makes it work.

**Comment by ghost** [comment]
I just created a repo with the bare bones code to reproduce the issue:

https://github.com/mwildehahn/gmailr-requirejs-debug

I added logging within gmailr to determine if we're overriding XMLHttpRequest functions properly. As it is now, those messages never get logged. The observations the app sets up don't work either (message sent and draft saved).

I really appreciate the help here. I've almost thrown my computer out the window several times over the past few days trying to figure out WTF is going on and how to fix it.

**Comment by joscha** [comment]
Hey @mwildehahn, I had a look at your repo and tried fixing it. Unfortuntely I am not sure if it even works with requireJS the way it is set up, because of the following:

GMailr overrides the XMLHttpRequest object of the frame where the drafts, etc. get saved. In order to do this, GMailr has to run in the context of that frame, e.g. it has to be injected into the website via `<script>` (thats what yepnope does and thats why it works with yepnope). Your repository however loads requireJS from within the Chrome extension - meaning that the JS files that get loaded run within the scope of the extension, not within the actual frame of GMail. Therefore the replacement of the XMLHttpRequest object fails (or rather it works, but the wrong object gets replaced) and thats why Drafts, etc. don't get recognized.

**Comment by joscha** [comment]
To make it work you would need to run requireJS from within the page, the problem with that however is, that the baseURL would still need to be set to `chrome.extension.getURL('src/js/')` which is not possible, because `chrome.extension` is not available within the page. You might be able to come up with a messaging solution using a background page though, that constructs the correct URLs for you.

**Comment by joscha** [comment]
I forked your repo and made it work using an ugly trick to find out the chrome extension base URL - you might want to find a cleaner way to do this, but at least it works. See https://github.com/mwildehahn/gmailr-requirejs-debug/pull/1/files

**Comment by ghost** [comment]
you're the man. thanks for spending the time to do this. i'll let you know if I come up with a cleaner way.

**Comment by joscha** [comment]
:+1:
