### ISSUE TITLE
Is this library still supported in latest chrome browser and maintained

### ISSUE THREAD

**Issue by ajays1991** [joscha/gmailr#4]
Hi,

Sorry for adding an issue. But i was looking through this extension to build another extension and want to implement my own extension. The api exposed suits very well my usecase.

Please update me if this lib is supported in latest chrome browser and still maintained before i head on toward implementing this in my code.

thanks

**Comment by joscha** [comment]
Hi @ajays1991,

It is still used in this extension here: http://www.mailfred.de/ and it is working fine in the latest Chrome and GMail. Having said that, the lib didn't need any updates in the last years and I am not sure how much time I would invest if it were to break, given that very few people use it.

**Comment by ajays1991** [comment]
Thanks for reply, i am closing this issue.
